/**
 * Single-language admin copy (Vietnamese).
 * Admin does not use next-intl — keep storefront i18n separate.
 */

export const adminCopy = {
  brand: "Green Garden",
  brandSubtitle: "Quản trị",
  navigation: {
    overview: "Tổng quan",
    plants: "Cây trồng",
    categories: "Danh mục",
    orders: "Đơn hàng",
    blog: "Blog",
    management: "Quản lý",
    customers: "Khách hàng",
    admins: "Quản trị viên",
    settings: "Cài đặt",
    help: "Trợ giúp / Hỗ trợ",
    helpDescription: "Cần hỗ trợ quản lý danh mục cây hoặc đơn hàng?",
    helpCta: "Liên hệ hỗ trợ",
    mainNav: "Điều hướng quản trị",
    openMenu: "Mở menu quản trị",
    closeMenu: "Đóng menu quản trị",
  },
  topbar: {
    notifications: "Thông báo",
    profile: "Hồ sơ quản trị",
    profileName: "Admin",
    profileEmail: "admin@example.com",
    viewStore: "Xem cửa hàng",
    signOut: "Đăng xuất",
  },
  common: {
    search: "Tìm kiếm",
    actions: "Thao tác",
    edit: "Sửa",
    view: "Xem",
    save: "Lưu",
    cancel: "Hủy",
    create: "Tạo",
    loading: "Đang tải...",
    saving: "Đang lưu...",
    previous: "Trước",
    next: "Sau",
    allStatuses: "Tất cả trạng thái",
    allCategories: "Tất cả danh mục",
    allDates: "Tất cả ngày",
    last7Days: "7 ngày qua",
    last30Days: "30 ngày qua",
    dateRange: "Khoảng thời gian",
    filters: "Bộ lọc",
    noResults: "Không có kết quả.",
    comingSoon: "Sắp ra mắt",
    placeholderDescription:
      "Phần này là giao diện tạm cho bản phát hành sau.",
    apiUnavailable: "API chưa khả dụng",
    apiUnavailableDescription: (endpoint: string) =>
      `Giao diện giữ nguyên. Backend chưa có endpoint ${endpoint}.`,
  },
  status: {
    active: "Đang hoạt động",
    inactive: "Ngừng hoạt động",
    draft: "Nháp",
    low_stock: "Sắp hết",
    out_of_stock: "Hết hàng",
    pending: "Chờ xử lý",
    processing: "Đang xử lý",
    shipped: "Đã gửi",
    delivered: "Đã giao",
    cancelled: "Đã hủy",
    paid: "Đã thanh toán",
    refunded: "Đã hoàn tiền",
    published: "Đã xuất bản",
    scheduled: "Đã lên lịch",
  },
  dashboard: {
    title: "Tổng quan",
    description: "Tổng quan cửa hàng Green Garden của bạn.",
    stats: {
      plants: "Tổng số cây",
      orders: "Đơn hàng",
      revenue: "Doanh thu",
      customers: "Khách hàng",
      plantsChange: "+8 tháng này",
      ordersChange: "+12% tháng này",
      revenueChange: "+8.4%",
      customersChange: "+15 tháng này",
    },
    recentOrders: {
      title: "Đơn hàng gần đây",
      description: "Các đơn hàng mới nhất từ khách hàng.",
      viewAll: "Xem tất cả",
    },
    inventory: {
      title: "Tồn kho cây",
      description: "Xem nhanh mức tồn kho.",
      viewAll: "Xem tất cả",
      stock: (count: number) => `${count} còn hàng`,
    },
    sales: {
      title: "Doanh số",
      description: "Đơn hàng tuần này (dữ liệu mẫu).",
    },
    table: {
      order: "Đơn hàng",
      customer: "Khách hàng",
      items: "Sản phẩm",
      total: "Tổng",
      status: "Trạng thái",
      date: "Ngày",
      plant: "Cây",
      stock: "Tồn kho",
    },
  },
  plants: {
    title: "Cây trồng",
    description: "Quản lý danh mục cây của Green Garden.",
    add: "Thêm cây",
    searchPlaceholder: "Tìm cây...",
    table: {
      plant: "Cây",
      category: "Danh mục",
      price: "Giá",
      stock: "Tồn kho",
      status: "Trạng thái",
      updated: "Cập nhật",
    },
  },
  categories: {
    title: "Danh mục",
    description: "Tổ chức cây theo danh mục để khách dễ duyệt.",
    add: "Thêm danh mục",
    table: {
      category: "Danh mục",
      plants: "Số cây",
      status: "Trạng thái",
      updated: "Cập nhật",
    },
  },
  orders: {
    title: "Đơn hàng",
    description: "Theo dõi và xử lý đơn hàng khách hàng.",
    searchPlaceholder: "Tìm đơn hoặc khách hàng...",
    table: {
      orderId: "Mã đơn",
      customer: "Khách hàng",
      items: "Sản phẩm",
      total: "Tổng",
      payment: "Thanh toán",
      status: "Trạng thái",
      date: "Ngày",
    },
  },
  blog: {
    title: "Blog",
    description: "Quản lý bài hướng dẫn chăm sóc và câu chuyện vườn ươm.",
    add: "Thêm bài viết",
    searchPlaceholder: "Tìm bài viết...",
    table: {
      title: "Tiêu đề",
      status: "Trạng thái",
      author: "Tác giả",
      published: "Xuất bản",
      updated: "Cập nhật",
    },
    unpublished: "—",
  },
  customers: {
    title: "Khách hàng",
    description: "Quản lý khách hàng sẽ có trong bản phát hành sau.",
  },
  admins: {
    title: "Quản trị viên",
    description: "Quản lý tài khoản quản trị Green Garden.",
    add: "Thêm quản trị viên",
    empty: "Chưa có quản trị viên nào.",
    createTitle: "Tạo quản trị viên",
    editTitle: "Sửa quản trị viên",
    passwordTitle: "Đổi mật khẩu",
    name: "Họ tên",
    email: "Email",
    password: "Mật khẩu",
    newPassword: "Mật khẩu mới",
    status: "Trạng thái",
    created: "Ngày tạo",
    updated: "Cập nhật",
    activate: "Kích hoạt",
    deactivate: "Vô hiệu hóa",
    changePassword: "Đổi mật khẩu",
    createdSuccess: "Đã tạo quản trị viên.",
    updatedSuccess: "Đã cập nhật quản trị viên.",
    statusSuccess: "Đã cập nhật trạng thái.",
    passwordSuccess: "Đã đổi mật khẩu.",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Trang ${page}/${totalPages} · ${total} quản trị viên`,
    table: {
      name: "Họ tên",
      email: "Email",
      status: "Trạng thái",
      created: "Ngày tạo",
      updated: "Cập nhật",
    },
  },
  settings: {
    title: "Cài đặt",
    description: "Cài đặt cửa hàng và quản trị sẽ có trong bản phát hành sau.",
  },
  login: {
    title: "Đăng nhập quản trị",
    description: "Đăng nhập để quản lý cửa hàng Green Garden.",
    email: "Email",
    password: "Mật khẩu",
    submit: "Đăng nhập",
    submitting: "Đang đăng nhập...",
    error: "Invalid email or password.",
    validationError: "Please check the form and try again.",
    networkError: "Unable to sign in. Please try again.",
  },
} as const;

export type AdminStatusKey = keyof typeof adminCopy.status;
