/**
 * Single-language admin copy (English).
 * Admin does not use next-intl — keep storefront i18n separate.
 */

export const adminCopy = {
  brand: "Ngoc Ngan Ben Tre",
  brandSubtitle: "Admin",
  navigation: {
    overview: "Overview",
    plants: "Plants",
    categories: "Categories",
    orders: "Orders",
    management: "Management",
    customers: "Customers",
    admins: "Admins",
    settings: "Settings",
    mainNav: "Admin navigation",
    openMenu: "Open admin menu",
    closeMenu: "Close admin menu",
  },
  topbar: {
    notifications: "Notifications",
    profile: "Admin profile",
    profileName: "Admin",
    profileEmail: "admin@example.com",
    viewStore: "View store",
    signOut: "Sign out",
  },
  common: {
    search: "Search",
    actions: "Actions",
    edit: "Edit",
    view: "View",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    loading: "Loading...",
    saving: "Saving...",
    previous: "Previous",
    next: "Next",
    allStatuses: "All statuses",
    allCategories: "All categories",
    allDates: "All dates",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    dateRange: "Date range",
    filters: "Filters",
    noResults: "No results.",
    comingSoon: "Coming soon",
    placeholderDescription:
      "This section is a placeholder for a later release.",
    apiUnavailable: "API unavailable",
    apiUnavailableDescription: (endpoint: string) =>
      `UI kept as-is. Backend does not expose ${endpoint} yet.`,
  },
  status: {
    active: "Active",
    inactive: "Inactive",
    draft: "Draft",
    low_stock: "Low stock",
    out_of_stock: "Out of stock",
    pending: "Pending",
    confirmed: "Confirmed",
    processing: "Processing",
    shipping: "Shipping",
    completed: "Completed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    paid: "Paid",
    refunded: "Refunded",
    published: "Published",
    scheduled: "Scheduled",
  },
  dashboard: {
    title: "Overview",
    description: "Overview of your Ngoc Ngan Ben Tre store.",
    loadError: "Unable to load the dashboard statistics.",
    retry: "Retry",
    stats: {
      plants: "Total plants",
      orders: "Orders",
      revenue: "Revenue",
      customers: "Customers",
      activePlants: (count: number) => `${count} active`,
      activeCustomers: (count: number) => `${count} active`,
      pendingOrders: (count: number) => `${count} pending`,
      revenueHint: "Completed orders",
    },
    sales: {
      title: "Sales",
      description: "Orders created and the revenue completed ones earned.",
      today: "Today",
      thisMonth: "This month",
      orders: "Orders",
      revenue: "Revenue",
    },
    revenue: {
      title: "Revenue",
      description: "Completed-order revenue for each day this month.",
      empty: "No revenue recorded this month yet.",
      /** Bars are unlabelled on their own; this describes the whole chart. */
      chartLabel: "Daily revenue this month",
      day: (date: string, revenue: string) => `${date}: ${revenue}`,
    },
    ordersByStatus: {
      title: "Orders by status",
      description: "Every order, grouped by its current status.",
    },
    topPlants: {
      title: "Top plants",
      description: "Best sellers across completed orders.",
      empty: "No plants have sold yet.",
      viewAll: "View all",
      sold: (count: number) => `${count} sold`,
    },
    lowStock: {
      title: "Low stock",
      description: "Active plants running low.",
      empty: "Every active plant is well stocked.",
      viewAll: "View all",
      stock: (count: number) => `${count} in stock`,
    },
    recentOrders: {
      title: "Recent orders",
      description: "Latest orders from customers.",
      viewAll: "View all",
      empty: "No orders yet.",
    },
    table: {
      order: "Order",
      customer: "Customer",
      total: "Total",
      status: "Status",
      date: "Date",
    },
  },
  plants: {
    title: "Plants",
    description: "Manage the Ngoc Ngan Ben Tre plant catalog.",
    add: "Add plant",
    searchPlaceholder: "Search name or SKU...",
    empty: "No plants yet.",
    noResults: "No plants match your filters.",
    createTitle: "Create plant",
    editTitle: "Edit plant",
    noImage: "No image",
    createdSuccess: "Plant created.",
    updatedSuccess: "Plant updated.",
    activatedSuccess: "Plant activated.",
    deactivatedSuccess: "Plant deactivated.",
    activate: "Activate",
    deactivate: "Deactivate",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Page ${page}/${totalPages} · ${total} plants`,
    sections: {
      basics: "Basic information",
      pricing: "Pricing & inventory",
      images: "Images",
      potSizes: "Pot sizes",
    },
    fields: {
      category: "Category",
      categoryPlaceholder: "Select a category",
      name: "Name (English)",
      nameVi: "Name (Vietnamese)",
      slug: "Slug",
      description: "Description (English)",
      descriptionVi: "Description (Vietnamese)",
      sku: "SKU",
      price: "Price (USD)",
      priceVi: "Price (VND)",
      stock: "Stock",
      featured: "Featured",
      featuredHint: "Highlighted on the storefront.",
      active: "Active",
      activeHint: "Visible in the storefront.",
    },
    filters: {
      allCategories: "All categories",
      allPlants: "All plants",
      featuredOnly: "Featured only",
      notFeatured: "Not featured",
      minPrice: "Min price",
      maxPrice: "Max price",
      sortNewest: "Newest",
      sortName: "Name",
      sortPrice: "Price",
      sortStock: "Stock",
      sortLabel: "Sort by",
      orderLabel: "Order",
      ascending: "Ascending",
      descending: "Descending",
      reset: "Reset filters",
    },
    invalidCategory: "Category is required.",
    invalidName: "Name is required (1-255 characters).",
    invalidNameVi: "Vietnamese name must be 255 characters or fewer.",
    invalidSlug: "Slug is required (1-255 characters).",
    invalidSku: "SKU is required (1-100 characters).",
    invalidPrice: "Price must be a number of 0 or more.",
    invalidPriceVi: "Vietnamese price must be a number of 0 or more.",
    invalidStock: "Stock must be a whole number of 0 or more.",
    categoriesLoadError: "Unable to load categories.",
    table: {
      plant: "Plant",
      category: "Category",
      sku: "SKU",
      price: "Price",
      stock: "Stock",
      status: "Status",
      updated: "Updated",
    },
    images: {
      title: "Images",
      description: "Add media by URL. Files are not uploaded to the database.",
      empty: "No images yet.",
      url: "Media URL",
      type: "Type",
      typeImage: "Image",
      typeVideo: "Video",
      altText: "Alt text",
      add: "Add image",
      adding: "Adding...",
      moveUp: "Move up",
      moveDown: "Move down",
      delete: "Delete image",
      addedSuccess: "Image added.",
      updatedSuccess: "Image updated.",
      deletedSuccess: "Image deleted.",
      reorderedSuccess: "Images reordered.",
      invalidUrl: "Media URL must be a valid URL.",
      availableAfterCreate: "Images can be added after the plant is created.",
    },
    potSizes: {
      title: "Pot sizes",
      description: "Price adjustments are added on top of the base price.",
      empty: "No pot sizes yet.",
      name: "Name",
      adjustment: "Adjustment (USD)",
      adjustmentVi: "Adjustment (VND)",
      add: "Add pot size",
      adding: "Adding...",
      delete: "Delete pot size",
      activate: "Activate",
      deactivate: "Deactivate",
      addedSuccess: "Pot size added.",
      updatedSuccess: "Pot size updated.",
      deletedSuccess: "Pot size deleted.",
      moveUp: "Move up",
      moveDown: "Move down",
      invalidName: "Pot size name is required (1-100 characters).",
      invalidAdjustment: "Adjustment must be a number of 0 or more.",
      availableAfterCreate:
        "Pot sizes can be added after the plant is created.",
    },
  },
  categories: {
    title: "Categories",
    description: "Organize plants into categories for easier browsing.",
    add: "Add category",
    searchPlaceholder: "Search name or slug...",
    empty: "No categories yet.",
    noResults: "No categories match your filters.",
    createTitle: "Create category",
    editTitle: "Edit category",
    nameVi: "Vietnamese name",
    descriptionVi: "Vietnamese description",
    imageUrl: "Image URL",
    active: "Active",
    activeHint: "Visible in the storefront.",
    noImage: "No image",
    createdSuccess: "Category created.",
    updatedSuccess: "Category updated.",
    activatedSuccess: "Category activated.",
    deactivatedSuccess: "Category deactivated.",
    activate: "Activate",
    deactivate: "Deactivate",
    invalidName: "Name is required (1-255 characters).",
    invalidNameVi: "Vietnamese name must be 255 characters or fewer.",
    invalidSlug: "Slug is required (1-255 characters).",
    invalidSortOrder: "Sort order must be an integer of 0 or more.",
    invalidImageUrl: "Image URL must be a valid URL.",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Page ${page}/${totalPages} · ${total} categories`,
    table: {
      image: "Image",
      name: "Name",
      slug: "Slug",
      description: "Description",
      sortOrder: "Sort order",
      status: "Status",
    },
  },
  orders: {
    title: "Orders",
    description: "Track and process customer orders.",
    add: "Create order",
    searchPlaceholder: "Search order number, name or phone...",
    empty: "No orders yet.",
    noResults: "No orders match your filters.",
    createTitle: "Create order",
    detailTitle: "Order detail",
    allStatuses: "All statuses",
    dateFrom: "From date",
    dateTo: "To date",
    reset: "Reset filters",
    createdSuccess: "Order created.",
    statusSuccess: "Order status updated.",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Page ${page}/${totalPages} · ${total} orders`,
    itemCount: (count: number) => (count === 1 ? "1 item" : `${count} items`),
    fields: {
      orderNumber: "Order number",
      customerName: "Customer name",
      customerPhone: "Phone",
      customerEmail: "Email",
      status: "Status",
      shippingAddress: "Shipping address",
      note: "Note",
      created: "Created",
      updated: "Updated",
      totalAmount: "Total",
      totalHint: "Calculated by the backend.",
    },
    items: {
      title: "Items",
      plant: "Plant",
      potSize: "Pot size",
      quantity: "Qty",
      unitPrice: "Unit price",
      empty: "No items on this order.",
      add: "Add item",
      remove: "Remove item",
      selectPlant: "Select a plant",
      noPotSize: "No pot size",
      priceHint: "Prices and stock are resolved by the backend.",
      required: "Add at least one item.",
    },
    invalidCustomerName: "Customer name is required (1-255 characters).",
    invalidCustomerPhone: "Phone is required (1-32 characters).",
    invalidEmail: "Enter a valid email address.",
    invalidShippingAddress: "Shipping address is required.",
    invalidQuantity: "Quantity must be a whole number of 1 or more.",
    plantsLoadError: "Unable to load plants.",
    table: {
      orderNumber: "Order",
      customer: "Customer",
      items: "Items",
      total: "Total",
      status: "Status",
      date: "Date",
    },
  },
  customers: {
    title: "Customers",
    description: "Manage customer records and review their order history.",
    add: "Add customer",
    searchPlaceholder: "Search name, phone or email...",
    empty: "No customers yet.",
    noResults: "No customers match your filters.",
    createTitle: "Create customer",
    editTitle: "Edit customer",
    detailTitle: "Customer detail",
    activate: "Activate",
    deactivate: "Deactivate",
    createdSuccess: "Customer created.",
    updatedSuccess: "Customer updated.",
    activatedSuccess: "Customer activated.",
    deactivatedSuccess: "Customer deactivated.",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Page ${page}/${totalPages} · ${total} customers`,
    fields: {
      name: "Name",
      phone: "Phone",
      email: "Email",
      emailHint: "Optional.",
      status: "Status",
      created: "Created",
      updated: "Updated",
    },
    orders: {
      title: "Order history",
      empty: "This customer has no orders yet.",
      loadError: "Unable to load this customer's orders.",
      viewAll: (total: number) =>
        total === 1 ? "1 order" : `${total} orders`,
    },
    invalidName: "Name is required (1-255 characters).",
    invalidPhone: "Phone is required (1-32 characters).",
    invalidEmail: "Enter a valid email address.",
    table: {
      name: "Name",
      phone: "Phone",
      email: "Email",
      status: "Status",
      created: "Created",
    },
  },
  admins: {
    title: "Admins",
    description: "Manage Ngoc Ngan Ben Tre admin accounts.",
    add: "Add admin",
    empty: "No admins yet.",
    createTitle: "Create admin",
    editTitle: "Edit admin",
    passwordTitle: "Change password",
    name: "Name",
    email: "Email",
    password: "Password",
    newPassword: "New password",
    status: "Status",
    created: "Created",
    updated: "Updated",
    activate: "Activate",
    deactivate: "Deactivate",
    changePassword: "Change password",
    createdSuccess: "Admin created.",
    updatedSuccess: "Admin updated.",
    statusSuccess: "Status updated.",
    passwordSuccess: "Password updated.",
    pageInfo: (page: number, totalPages: number, total: number) =>
      `Page ${page}/${totalPages} · ${total} admins`,
    table: {
      name: "Name",
      email: "Email",
      status: "Status",
      created: "Created",
      updated: "Updated",
    },
  },
  settings: {
    title: "Settings",
    description: "Store and admin settings will be available in a later release.",
  },
  login: {
    title: "Admin sign in",
    description: "Sign in to manage the Ngoc Ngan Ben Tre store.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in...",
    error: "Invalid email or password.",
    validationError: "Please check the form and try again.",
    networkError: "Unable to sign in. Please try again.",
  },
} as const;

export type AdminStatusKey = keyof typeof adminCopy.status;
